/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Comparator_Carros.*;
import Comparator_Manto.*;
import Clases.*;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author raul-pc
 */
public class carrosPanel extends javax.swing.JFrame {

    //TABLAS
    DefaultTableModel tablaCarros = new DefaultTableModel();
    DefaultTableModel tablaMantos = new DefaultTableModel();
    //ARRAYLIST
    ArrayList<Carros> lCarros = new ArrayList<>();
    ArrayList<Mantos> lMantos = new ArrayList<>();

    public void cargarTablas() {
        //Tabla Carros
        ArrayList<Object> lCabezaCarros = new ArrayList<>();
        lCabezaCarros.add("Placa");
        lCabezaCarros.add("Modelo");
        lCabezaCarros.add("Año");
        lCabezaCarros.add("Color");

        for (Object columns : lCabezaCarros) {
            tablaCarros.addColumn(columns);
        }
        tbVehiculos.setModel(tablaCarros);
        //Tabla Mantos
        ArrayList<Object> lCabezaMantos = new ArrayList<>();
        lCabezaMantos.add("Tipo");
        lCabezaMantos.add("Precio");
        lCabezaMantos.add("Fecha");
        for (Object columns : lCabezaMantos) {
            tablaMantos.addColumn(columns);
        }
        tbMantos.setModel(tablaMantos);

    }

    //RECARGAR TABLA CARROS
    private void recargarTablaCarros() {
        this.tablaCarros.setRowCount(0);
        for (int i = 0; i < this.lCarros.size(); i++) {
            String[] registro = {
                this.lCarros.get(i).getPlaca(),
                this.lCarros.get(i).getModelo(),
                this.lCarros.get(i).getAño() + "",
                this.lCarros.get(i).getColor()};
            tablaCarros.addRow(registro);
        }
    }

    //RECARGAR TABLA MANTOS
    private void recargarTablaMantos(int index) {
        this.tablaMantos.setRowCount(0);
        for (int i = 0; i < this.lCarros.get(index).getlMantenimientos().size(); i++) {
            String[] registro = {
                this.lCarros.get(index).getlMantenimientos().get(i).getTipoManto(),
                this.lCarros.get(index).getlMantenimientos().get(i).getPrecioManto() + "",
                this.lCarros.get(index).getlMantenimientos().get(i).getFechaManto() + ""
            };
            tablaMantos.addRow(registro);
        }
    }

    public carrosPanel() {
        initComponents();
        cargarTablas();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        descPlaca1 = new Comparator_Carros.DescPlaca();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        bnGenerar = new javax.swing.JToggleButton();
        spAutos = new javax.swing.JSpinner();
        spMantos = new javax.swing.JSpinner();
        jPanel6 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jbPlacaMayor = new javax.swing.JButton();
        jbModeloMayor = new javax.swing.JButton();
        jbAñoMayor = new javax.swing.JButton();
        jbColorMayor = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        jbPlacaMenor = new javax.swing.JButton();
        jbModeloMenor = new javax.swing.JButton();
        jbAñoMenor = new javax.swing.JButton();
        jbColorMenor = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jbTipoMayor = new javax.swing.JButton();
        jbPrecioMayor = new javax.swing.JButton();
        jbFechaMayor = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();
        jbTipoMenor = new javax.swing.JButton();
        jbPrecioMenor = new javax.swing.JButton();
        jbFechaMenor = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbVehiculos = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbMantos = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ordenamiento lista de autos");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)), "Añadir Datos"));
        jPanel1.setName("Añadir Datos"); // NOI18N

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel2.setText("Cantidad Autos");

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel3.setText("Cantidad Mantos");

        bnGenerar.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        bnGenerar.setText("GENERAR");
        bnGenerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnGenerarActionPerformed(evt);
            }
        });

        spAutos.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        spAutos.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));

        spMantos.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        spMantos.setModel(new javax.swing.SpinnerNumberModel(3, 3, null, 1));

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Tabla Vehículos"));

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Ordenar mayor"));

        jbPlacaMayor.setText("Placa");
        jbPlacaMayor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbPlacaMayorActionPerformed(evt);
            }
        });

        jbModeloMayor.setText("Modelo");
        jbModeloMayor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbModeloMayorActionPerformed(evt);
            }
        });

        jbAñoMayor.setText("Año");
        jbAñoMayor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAñoMayorActionPerformed(evt);
            }
        });

        jbColorMayor.setText("Color");
        jbColorMayor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbColorMayorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jbPlacaMayor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbModeloMayor, javax.swing.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jbAñoMayor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbColorMayor, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbAñoMayor, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbPlacaMayor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbModeloMayor)
                    .addComponent(jbColorMayor)))
        );

        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Ordenar menor"));

        jbPlacaMenor.setText("Placa");
        jbPlacaMenor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbPlacaMenorActionPerformed(evt);
            }
        });

        jbModeloMenor.setText("Modelo");
        jbModeloMenor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbModeloMenorActionPerformed(evt);
            }
        });

        jbAñoMenor.setText("Año");
        jbAñoMenor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAñoMenorActionPerformed(evt);
            }
        });

        jbColorMenor.setText("Color");
        jbColorMenor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbColorMenorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jbPlacaMenor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbModeloMenor, javax.swing.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jbAñoMenor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbColorMenor, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbAñoMenor, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbPlacaMenor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbModeloMenor)
                    .addComponent(jbColorMenor)))
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 16, Short.MAX_VALUE))
        );

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder("Tabla Mantos"));

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Ordenar Mayor"));

        jbTipoMayor.setText("Tipo");
        jbTipoMayor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbTipoMayorActionPerformed(evt);
            }
        });

        jbPrecioMayor.setText("Precio");
        jbPrecioMayor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbPrecioMayorActionPerformed(evt);
            }
        });

        jbFechaMayor.setText("Fecha");
        jbFechaMayor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbFechaMayorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jbPrecioMayor, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbTipoMayor, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbFechaMayor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(25, 25, 25))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(jbTipoMayor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbPrecioMayor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbFechaMayor)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel10.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Ordenar Mayor"));

        jbTipoMenor.setText("Tipo");
        jbTipoMenor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbTipoMenorActionPerformed(evt);
            }
        });

        jbPrecioMenor.setText("Precio");
        jbPrecioMenor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbPrecioMenorActionPerformed(evt);
            }
        });

        jbFechaMenor.setText("Fecha");
        jbFechaMenor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbFechaMenorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jbPrecioMenor, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbTipoMenor, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbFechaMenor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(25, 25, 25))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addComponent(jbTipoMenor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbPrecioMenor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbFechaMenor)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jPanel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(spAutos))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(spMantos))
                        .addGap(79, 79, 79))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(143, 143, 143)
                .addComponent(bnGenerar, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spAutos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spMantos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addComponent(bnGenerar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Vehículos"));

        tbVehiculos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dataTablaMantos(evt);
            }
        });
        jScrollPane1.setViewportView(tbVehiculos);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 562, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 233, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Mantos"));

        tbMantos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(tbMantos);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    //EL BOTON
    private void bnGenerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnGenerarActionPerformed
        tablaCarros.getDataVector().removeAllElements();
        tablaCarros.fireTableDataChanged();
        Carros oCarros;
        Mantos oManto;
        for (int i = 0; i < spAutos.getValue().hashCode(); i++) {
            //LLamar para asignar los datos
            //CREAR NUEVOS OBJETOS Y NUEVA LISTA
            oCarros = new Carros();
            lMantos = new ArrayList<>();
            oCarros.setPlaca();
            oCarros.setModelo();
            oCarros.setAño();
            oCarros.setColor();
            //Crear los valores de mantos
            for (int j = 0; j < spMantos.getValue().hashCode(); j++) {
                oManto = new Mantos();
                oManto.setTipoManto();
                oManto.setPrecioManto();
                oManto.setFechaManto();
                //Guardarlos en Arraylist de Mantos
                lMantos.add(oManto);
            }
            //Guardar ya todo
            oCarros.setlMantenimientos(lMantos);
            lCarros.add(oCarros);
        }
        //Reproducirlos en la tabla
        for (int j = 0; j < lCarros.size(); j++) {
            String[] rowAutos = {
                lCarros.get(j).getPlaca(),
                lCarros.get(j).getModelo(),
                lCarros.get(j).getAño() + "",
                lCarros.get(j).getColor()
            };
            //Aqui se inscriben
            tablaCarros.addRow(rowAutos);
        }
    }//GEN-LAST:event_bnGenerarActionPerformed

    private void dataTablaMantos(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dataTablaMantos
        tablaMantos.getDataVector().removeAllElements();
        tablaMantos.fireTableDataChanged();
        int index = tbVehiculos.getSelectedRow();
        for (int i = 0; i < lCarros.get(index).getlMantenimientos().size(); i++) {
            String[] rowMantos = {
                lCarros.get(index).getlMantenimientos().get(i).getTipoManto(),
                Double.toString(lCarros.get(index).getlMantenimientos().get(i).getPrecioManto()),
                lCarros.get(index).getlMantenimientos().get(i).getFechaManto() + ""
            };
            tablaMantos.addRow(rowMantos);
        }
    }//GEN-LAST:event_dataTablaMantos

    private void jbColorMayorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbColorMayorActionPerformed
        //ORDENAR COLOR
        AscColor asccolor = new AscColor();
        lCarros.sort(asccolor);
        recargarTablaCarros();
    }//GEN-LAST:event_jbColorMayorActionPerformed

    private void jbColorMenorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbColorMenorActionPerformed
        //ORDENAR COLOR
        DescColor desccolor = new DescColor();
        lCarros.sort(desccolor);
        recargarTablaCarros();
    }//GEN-LAST:event_jbColorMenorActionPerformed

    private void jbModeloMenorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbModeloMenorActionPerformed
        //ORDENAR MODELO
        DescModelo descmodelo = new DescModelo();
        lCarros.sort(descmodelo);
        recargarTablaCarros();
    }//GEN-LAST:event_jbModeloMenorActionPerformed

    private void jbFechaMayorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbFechaMayorActionPerformed
        //ORDENAR FECHA
        int index = tbVehiculos.getSelectedRow();
        AscFecha ascfecha = new AscFecha();
        lCarros.get(index).getlMantenimientos().sort(ascfecha);
        recargarTablaMantos(index);
    }//GEN-LAST:event_jbFechaMayorActionPerformed

    private void jbPlacaMayorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbPlacaMayorActionPerformed
        //ORDENAR PLACA
        AscPlaca ascplaca = new AscPlaca();
        lCarros.sort(ascplaca);
        recargarTablaCarros();
    }//GEN-LAST:event_jbPlacaMayorActionPerformed

    private void jbPlacaMenorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbPlacaMenorActionPerformed
        //ORDENAR PLACA
        DescPlaca descplaca = new DescPlaca();
        lCarros.sort(descplaca);
        recargarTablaCarros();
    }//GEN-LAST:event_jbPlacaMenorActionPerformed

    private void jbAñoMayorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAñoMayorActionPerformed
        //ORDENAR AÑO
        AscAño ascaño = new AscAño();
        lCarros.sort(ascaño);
        recargarTablaCarros();
    }//GEN-LAST:event_jbAñoMayorActionPerformed

    private void jbAñoMenorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAñoMenorActionPerformed
        //ORDENAR AÑO
        DescAño descaño = new DescAño();
        lCarros.sort(descaño);
        recargarTablaCarros();
    }//GEN-LAST:event_jbAñoMenorActionPerformed

    private void jbModeloMayorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbModeloMayorActionPerformed
        //ORDENAR MODELO
        AscModelo ascmodelo = new AscModelo();
        lCarros.sort(ascmodelo);
        recargarTablaCarros();
    }//GEN-LAST:event_jbModeloMayorActionPerformed

    private void jbTipoMayorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbTipoMayorActionPerformed
        //ORDENAR TIPO MANTO
        int index = tbVehiculos.getSelectedRow();
        AscTipoManto asctipomanto = new AscTipoManto();
        lCarros.get(index).getlMantenimientos().sort(asctipomanto);
        recargarTablaMantos(index);
    }//GEN-LAST:event_jbTipoMayorActionPerformed

    private void jbTipoMenorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbTipoMenorActionPerformed
        //ORDENAR TIPO MANTO
        int index = tbVehiculos.getSelectedRow();
        DescTipoManto desctipomanto = new DescTipoManto();
        lCarros.get(index).getlMantenimientos().sort(desctipomanto);
        recargarTablaMantos(index);
    }//GEN-LAST:event_jbTipoMenorActionPerformed

    private void jbPrecioMayorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbPrecioMayorActionPerformed
        //ORDENAR PRECIO DE MANTOS
        int index = tbVehiculos.getSelectedRow();
        AscPrecio ascprecio = new AscPrecio();
        lCarros.get(index).getlMantenimientos().sort(ascprecio);
        recargarTablaMantos(index);
    }//GEN-LAST:event_jbPrecioMayorActionPerformed

    private void jbPrecioMenorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbPrecioMenorActionPerformed
        //ORDENAR PRECIO DE MANTOS
        int index = tbVehiculos.getSelectedRow();
        DescPrecio descprecio = new DescPrecio();
        lCarros.get(index).getlMantenimientos().sort(descprecio);
        recargarTablaMantos(index);
    }//GEN-LAST:event_jbPrecioMenorActionPerformed

    private void jbFechaMenorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbFechaMenorActionPerformed
        //ORDENAR FECHA
        int index = tbVehiculos.getSelectedRow();
        DescFecha descfecha = new DescFecha();
        lCarros.get(index).getlMantenimientos().sort(descfecha);
        recargarTablaMantos(index);
    }//GEN-LAST:event_jbFechaMenorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(carrosPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(carrosPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(carrosPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(carrosPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new carrosPanel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton bnGenerar;
    private Comparator_Carros.DescPlaca descPlaca1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton jbAñoMayor;
    private javax.swing.JButton jbAñoMenor;
    private javax.swing.JButton jbColorMayor;
    private javax.swing.JButton jbColorMenor;
    private javax.swing.JButton jbFechaMayor;
    private javax.swing.JButton jbFechaMenor;
    private javax.swing.JButton jbModeloMayor;
    private javax.swing.JButton jbModeloMenor;
    private javax.swing.JButton jbPlacaMayor;
    private javax.swing.JButton jbPlacaMenor;
    private javax.swing.JButton jbPrecioMayor;
    private javax.swing.JButton jbPrecioMenor;
    private javax.swing.JButton jbTipoMayor;
    private javax.swing.JButton jbTipoMenor;
    private javax.swing.JSpinner spAutos;
    private javax.swing.JSpinner spMantos;
    private javax.swing.JTable tbMantos;
    private javax.swing.JTable tbVehiculos;
    // End of variables declaration//GEN-END:variables
}
